Fix recursion bug in ControlCollection
tomwendel/monogameui pull request #42
Opened 2018-03-13 15:02 UTC by ManuelHu

Aus OctoAwesome/octoawesome#250:

> Warum das hier so langsam läuft... Ein Schleifendurchlauf dauert 25s! Mal schnell durchprofilert: Liegt an MonoGameUI (`ControlCollection.Add`), was heftig CPU-Zeit verbrät. MonoGameUi wurde ja auch in deisem Pull Request upgedated, könnte es daran liegen?

> ![grafik](https://user-images.githubusercontent.com/10050780/37294911-3b44ce4e-2617-11e8-9b36-c3b2440aa4b2.png)
> Weiteres Profiling: CPU-Zeit wird fast 1:1 von `ControlCollection.ReorderZ` verbraten. Und hier wird es komisch: Vom profiling siehts fast so aus, als wäre die Methode rekursiv:
![grafik](https://user-images.githubusercontent.com/10050780/37295640-f89cb5fa-2618-11e8-8dd5-7de8910b35b6.png)

> Aber ich sehe jetzt auf den ersten Blick auch noch nicht, wo diese rekursivität her kommt: Vielleicht so: In ReorderZ wird der ZIndex der Controls geändert. Das feuert das ein  Event, wo der Handler item_ZOrderChanged registriert ist, der wiederum `ReorderZ` aufruft...

> Performance: Das MonoGameUI-Issue, das hat was mit deinem Changeset (speziell dem Update von MonoGameUi)  zu tun. Sonst kommen wir ja noch nicht mal dazu die Schatten zu sehen...  Ich habe aber eine starke Vermutung, woran es liegt, und einen einfachen (aber unsauberen...) Weg es zu lösen:

> ![grafik](https://user-images.githubusercontent.com/10050780/37301243-502b0f9c-2628-11e8-9452-348983c748cc.png)
>Hier der [MonoGameUi-Code *vor* dem Update.](https://github.com/OctoAwesome/monogameui/blob/56025fd848de0590749407b4381be91ffae728b8/MonoGameUi/ControlCollection.cs#L145-L160) Da InZOrder vor dem Sortieren auf null gesetzt wird, kommt es nie zur Rekursion (vgl. markierte Zeilen)

>In der jetzigen Version wird die Liste nicht mehr in der Methode gesetzt (auch nicht auf null). Daher kommt es zur Rekursion.

>Einfacher Quick&Dirty Fix wäre das Einfügen eines bools, der speichert, ob gerade neu sortiert wird...

Genau diesen Fix habe ich hier umgesetzt.

2018-03-14 06:19 UTC, CsharpLassi commented
Danke, dafür das.

2018-03-14 06:22 UTC, XYZLassi requested changes

2018-03-14 06:22 UTC, CsharpLassi commented on MonoGameUi/ControlCollection.cs
> +            isDoingUpdate = true;
Vielleicht hier auch noch mal die Abfrage isDoingUpdate, bzw raus aus item_ZOrder und dort hin.
Und Eventuell Thread-Safe machen(kann das passieren)???

2018-03-14 20:32 UTC, ManuelHu commented on MonoGameUi/ControlCollection.cs
> +            isDoingUpdate = true;
Man kann schon probieren, mit mehreren Threads auf MonoGameUi zuzgreifen - das wird aber mehr scheitern als hier... Ich stelle ja auch nur den alten Status quo wieder her, der war auch nicht Threadsafe. Den Rest habe ich gerade korrigiert

2018-03-20 17:40 UTC, CsharpLassi commented
Achso, danke wieder vergessen.
Spricht was dagegen das zu übernhemen ??

2018-03-20 17:41 UTC, XYZLassi approved these changes

2018-03-20 17:41 UTC, merged